# Generated by Django 5.2.8 on 2025-11-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_especificado', 'No especificado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.BigIntegerField(),
        ),
    ]
