# Generated by Django 5.2.8 on 2025-11-11 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_novedad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novedad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='juanito@porelmomento', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='capacidad_maxima',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hogares_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nino',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'masculino'), ('femenino', 'femenino'), ('otro', 'otro'), ('no_especificado', 'no_especificado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
