# Generated by Django 5.2.8 on 2025-11-11 23:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_novedad_usuario_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='documento_tenencia_pdf',
            field=models.FileField(blank=True, null=True, upload_to='hogares/documentos_tenencia/'),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='estrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='fotos_exterior',
            field=models.FileField(blank=True, null=True, upload_to='hogares/fotos_exterior/'),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='fotos_interior',
            field=models.FileField(blank=True, null=True, upload_to='hogares/fotos_interior/'),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='geolocalizacion_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='geolocalizacion_lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='material_construccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='num_banos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='num_habitaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='riesgos_cercanos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='tipo_tenencia',
            field=models.CharField(blank=True, choices=[('Propia', 'Propia'), ('Arrendada', 'Arrendada'), ('Comodato', 'Comodato')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nino',
            name='carnet_vacunacion',
            field=models.FileField(blank=True, null=True, upload_to='ninos/vacunacion/'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='certificado_eps',
            field=models.FileField(blank=True, null=True, upload_to='ninos/eps/'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='ninos/fotos/'),
        ),
        migrations.AlterField(
            model_name='padre',
            name='estrato',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ConvivienteHogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField()),
                ('edad', models.IntegerField()),
                ('parentesco', models.CharField(max_length=50)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convivientes', to='core.hogarcomunitario')),
            ],
            options={
                'db_table': 'convivientes_hogar',
            },
        ),
        migrations.CreateModel(
            name='MadreComunitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_escolaridad', models.CharField(choices=[('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Profesional', 'Profesional')], max_length=100)),
                ('titulo_obtenido', models.CharField(blank=True, max_length=150, null=True)),
                ('institucion', models.CharField(blank=True, max_length=150, null=True)),
                ('experiencia_previa', models.TextField(blank=True, null=True)),
                ('no_retirado_icbf', models.BooleanField(default=False)),
                ('disponibilidad_tiempo', models.BooleanField(default=False)),
                ('firma_digital', models.FileField(blank=True, null=True, upload_to='madres_documentos/firmas/')),
                ('documento_identidad_pdf', models.FileField(blank=True, null=True, upload_to='madres_documentos/cedulas/')),
                ('certificado_escolaridad_pdf', models.FileField(blank=True, null=True, upload_to='madres_documentos/educacion/')),
                ('certificado_antecedentes_pdf', models.FileField(blank=True, null=True, upload_to='madres_documentos/antecedentes/')),
                ('certificado_medico_pdf', models.FileField(blank=True, null=True, upload_to='madres_documentos/medico/')),
                ('certificado_residencia_pdf', models.FileField(blank=True, null=True, upload_to='madres_documentos/residencia/')),
                ('cartas_recomendacion_pdf', models.FileField(blank=True, null=True, upload_to='madres_documentos/recomendaciones/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='madre_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'madres_comunitarias',
            },
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hogares_asignados', to='core.madrecomunitaria'),
        ),
    ]
