# Generated by Django 5.2.7 on 2025-11-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_usuario_username_hogarcomunitario_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='capacidad_maxima',
            field=models.IntegerField(default=20),
        ),
    ]
