# Generated by Django 5.2.8 on 2025-11-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hogarcomunitario_capacidad_maxima'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesarrolloNino',
        ),
    ]
