# Generated by Django 5.2.8 on 2025-11-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_desarrollonino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='capacidad_maxima',
            field=models.IntegerField(default=15),
        ),
    ]
