# Generated by Django 5.2.8 on 2025-11-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_hogarcomunitario_capacidad_maxima'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Regional',
                'verbose_name_plural': 'Regionales',
                'db_table': 'regionales',
            },
        ),
        migrations.AddField(
            model_name='hogarcomunitario',
            name='regional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hogares', to='core.regional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='core.regional'),
        ),
    ]
