# Generated by Django 5.2.8 on 2025-11-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_regional_hogarcomunitario_regional_usuario_regional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='regional',
        ),
    ]
