# Generated by Django 5.2.8 on 2025-11-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_usuario_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='madrecomunitaria',
            name='foto_madre',
            field=models.FileField(blank=True, null=True, upload_to='madres_documentos/fotos/'),
        ),
    ]
