# Generated by Django 5.2.8 on 2025-11-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_madrecomunitaria_foto_madre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.regional'),
        ),
        migrations.AlterField(
            model_name='madrecomunitaria',
            name='foto_madre',
            field=models.ImageField(blank=True, null=True, upload_to='madres_documentos/fotos/'),
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='core.regional')),
            ],
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ciudad'),
        ),
    ]
