# Generated by Django 5.2.8 on 2025-11-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_hogarcomunitario_regional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_admin',
            field=models.ImageField(blank=True, null=True, upload_to='administradores/fotos/'),
        ),
    ]
