# Generated by Django 5.2.8 on 2025-11-16 00:30

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usuario_foto_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hogares', to='core.ciudad', null=True),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='localidad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hogares', to='core.regional', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_admin',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.admin_upload_path),
        ),
    ]
