# Generated by Django 5.2.8 on 2025-11-16

import core.models
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_set_hogarcomunitario_ciudad_regional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hogares', to='core.ciudad', null=False),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='direccion',
            field=models.CharField(max_length=200, null=False),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='localidad',
            field=models.CharField(max_length=100, null=False),
        ),
        migrations.AlterField(
            model_name='hogarcomunitario',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hogares', to='core.regional', null=False),
        ),
    ]
