# Generated by Django 5.2.8 on 2025-11-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_hogarcomunitario_fields_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Discapacidad',
                'verbose_name_plural': 'Discapacidades',
                'db_table': 'discapacidades',
            },
        ),
        migrations.AddField(
            model_name='nino',
            name='otra_discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor', 'Tutor'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='tiene_discapacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nino',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='tipos_discapacidad',
            field=models.ManyToManyField(blank=True, to='core.discapacidad'),
        ),
    ]
