# Generated by Django 5.2.8 on 2025-11-21 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_discapacidad_nino_otra_discapacidad_nino_parentesco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nino',
            name='registro_civil_img',
            field=models.FileField(blank=True, null=True, upload_to='ninos/registro_civil/'),
        ),
        migrations.AddField(
            model_name='padre',
            name='clasificacion_sisben',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='padre',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='padre',
            name='documento_identidad_img',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
