# Generated by Django 5.2.8 on 2025-11-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_nino_fecha_registro_nino_registro_civil_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='padre',
            name='otra_ocupacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
