# Generated by Django 5.2.8 on 2025-11-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_padre_otra_ocupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='otro_pais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otro país (especifique)'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('', '-- Seleccione el país de nacimiento --'), ('colombia', 'Colombia'), ('venezuela', 'Venezuela'), ('ecuador', 'Ecuador'), ('peru', 'Perú'), ('panama', 'Panamá'), ('brasil', 'Brasil'), ('argentina', 'Argentina'), ('chile', 'Chile'), ('bolivia', 'Bolivia'), ('paraguay', 'Paraguay'), ('uruguay', 'Uruguay'), ('mexico', 'México'), ('costa_rica', 'Costa Rica'), ('nicaragua', 'Nicaragua'), ('honduras', 'Honduras'), ('guatemala', 'Guatemala'), ('el_salvador', 'El Salvador'), ('cuba', 'Cuba'), ('republica_dominicana', 'República Dominicana'), ('haiti', 'Haití'), ('estados_unidos', 'Estados Unidos'), ('canada', 'Canadá'), ('espana', 'España'), ('italia', 'Italia'), ('francia', 'Francia'), ('alemania', 'Alemania'), ('otro', 'Otro país')], max_length=50, null=True, verbose_name='País de nacimiento'),
        ),
    ]
