# Generated by Django 5.2.8 on 2025-11-21 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_nino_otro_pais_alter_nino_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 1, 1), verbose_name='Fecha de ingreso al hogar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='padre',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('', '-- Seleccione una ocupación --'), ('empleado_publico', 'Empleado Público'), ('empleado_privado', 'Empleado Privado'), ('independiente', 'Trabajador Independiente'), ('comerciante', 'Comerciante'), ('agricultor', 'Agricultor'), ('constructor', 'Constructor/Albañil'), ('conductor', 'Conductor'), ('docente', 'Docente/Educador'), ('salud', 'Profesional de la Salud'), ('servicios', 'Servicios (Limpieza, Seguridad, etc.)'), ('domestico', 'Trabajador Doméstico'), ('estudiante', 'Estudiante'), ('pensionado', 'Pensionado'), ('desempleado', 'Desempleado'), ('ama_casa', 'Ama de Casa'), ('vendedor', 'Vendedor'), ('mecanico', 'Mecánico'), ('artesano', 'Artesano'), ('otro', 'Otro')], max_length=50, null=True),
        ),
    ]
