# Generated by Django 5.2.8 on 2025-11-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='correos_adjuntos/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('destinatarios', models.TextField(help_text='Correos separados por coma')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_con_exito', models.BooleanField(default=True)),
                ('nota_error', models.TextField(blank=True)),
                ('adjuntos', models.ManyToManyField(blank=True, to='correos.archivoadjunto')),
            ],
        ),
    ]
