# Generated by Django 5.2.8 on 2025-11-25 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_alter_nino_fecha_ingreso_alter_padre_ocupacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nino')),
            ],
        ),
    ]
