# Generated by Django 5.2.8 on 2025-11-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
