# Generated by Django 5.2.8 on 2025-11-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='novedades_pdfs/'),
        ),
    ]
