# Generated by Django 5.2.8 on 2025-11-07 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planeacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_experiencia', models.CharField(max_length=200)),
                ('intencionalidad_pedagogica', models.TextField()),
                ('materiales_utilizar', models.TextField()),
                ('ambiente_educativo', models.TextField()),
                ('experiencia_inicio', models.TextField()),
                ('experiencia_pedagogica', models.TextField()),
                ('cierre_experiencia', models.TextField()),
                ('situaciones_presentadas', models.TextField(help_text='Situaciones presentadas para el seguimiento de los niños y niñas')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
