# Generated by Django 5.2.8 on 2025-11-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeacion',
            name='situaciones_presentadas',
            field=models.TextField(),
        ),
    ]
