# Generated by Django 5.2.8 on 2025-11-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeaciones', '0002_alter_planeacion_situaciones_presentadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeacion',
            name='documentacion',
            field=models.ImageField(blank=True, null=True, upload_to='planeaciones/'),
        ),
    ]
