# Generated by Django 5.2.8 on 2025-11-13 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeaciones', '0003_planeacion_documentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planeacion',
            name='documentacion',
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='documentacion/')),
                ('planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='planeaciones.planeacion')),
            ],
        ),
    ]
