# Generated by Django 5.2.8 on 2025-11-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeaciones', '0004_remove_planeacion_documentacion_documentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='planeacion',
            name='dimensiones',
            field=models.ManyToManyField(blank=True, to='planeaciones.dimension'),
        ),
    ]
