# Generated by Django 5.2.8 on 2025-11-13 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_delete_desarrollonino'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesarrolloNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fin_mes', models.DateField()),
                ('dimension_cognitiva', models.TextField(verbose_name='Dimensión Cognitiva')),
                ('dimension_comunicativa', models.TextField(verbose_name='Dimensión Comunicativa')),
                ('dimension_socio_afectiva', models.TextField(verbose_name='Dimensión Socio-afectiva')),
                ('dimension_corporal', models.TextField(verbose_name='Dimensión Corporal')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desarrollos', to='core.nino')),
            ],
            options={
                'verbose_name': 'Desarrollo del Niño',
                'verbose_name_plural': 'Desarrollos de los Niños',
                'ordering': ['-fecha_fin_mes'],
            },
        ),
    ]
