# Generated by Django 5.2.8 on 2025-11-14 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollonino',
            name='rating_cognitiva',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating Dimensión Cognitiva'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='rating_comunicativa',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating Dimensión Comunicativa'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='rating_corporal',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating Dimensión Corporal'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='rating_socio_afectiva',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating Dimensión Socio-afectiva'),
        ),
    ]
