# Generated by Django 5.2.8 on 2025-11-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_desarrollonino_rating_cognitiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollonino',
            name='dimension_cognitiva',
            field=models.TextField(blank=True, null=True, verbose_name='Dimensión Cognitiva'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='dimension_comunicativa',
            field=models.TextField(blank=True, null=True, verbose_name='Dimensión Comunicativa'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='dimension_corporal',
            field=models.TextField(blank=True, null=True, verbose_name='Dimensión Corporal'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='dimension_socio_afectiva',
            field=models.TextField(blank=True, null=True, verbose_name='Dimensión Socio-afectiva'),
        ),
    ]
