# Generated by Django 5.2.8 on 2025-11-20 03:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_discapacidad_nino_otra_discapacidad_nino_parentesco_and_more'),
        ('desarrollo', '0003_alter_desarrollonino_dimension_cognitiva_and_more'),
        ('planeaciones', '0004_remove_planeacion_documentacion_documentacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desarrollonino',
            options={'ordering': ['-fecha_fin_mes', 'nino'], 'verbose_name': 'Desarrollo del Niño', 'verbose_name_plural': 'Desarrollos de los Niños'},
        ),
        migrations.AlterUniqueTogether(
            name='desarrollonino',
            unique_together={('nino', 'fecha_fin_mes')},
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='alertas_mes',
            field=models.TextField(blank=True, help_text='Alertas automáticas sobre inasistencias, valoraciones bajas o novedades.', null=True, verbose_name='Alertas del Mes'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='aspectos_a_mejorar',
            field=models.TextField(blank=True, help_text='Lista generada automáticamente de áreas de oportunidad.', null=True, verbose_name='Aspectos por Mejorar'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='comportamiento_frecuente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Comportamiento Más Frecuente'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='conclusion_general',
            field=models.TextField(blank=True, help_text='Resumen automático del progreso y estado general del niño en el mes.', null=True, verbose_name='Conclusión General del Desarrollo'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='evaluacion_autonomia',
            field=models.TextField(blank=True, null=True, verbose_name='Evaluación Autonomía'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='evaluacion_cognitiva',
            field=models.TextField(blank=True, null=True, verbose_name='Evaluación Cognitiva'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='evaluacion_comunicativa',
            field=models.TextField(blank=True, null=True, verbose_name='Evaluación Comunicativa / Lenguaje'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='evaluacion_corporal',
            field=models.TextField(blank=True, null=True, verbose_name='Evaluación Corporal / Motricidad'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='evaluacion_socio_afectiva',
            field=models.TextField(blank=True, null=True, verbose_name='Evaluación Socio-afectiva'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='fortalezas_mes',
            field=models.TextField(blank=True, help_text='Lista generada automáticamente de aspectos positivos.', null=True, verbose_name='Fortalezas del Mes'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, help_text='Espacio para notas o comentarios manuales del educador.', null=True, verbose_name='Observaciones Adicionales del Educador'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='participacion_frecuente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Participación Más Frecuente'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='recomendaciones_personales',
            field=models.TextField(blank=True, help_text='Recomendaciones específicas para la familia o el seguimiento.', null=True, verbose_name='Recomendaciones Personales'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='tendencia_valoracion',
            field=models.CharField(blank=True, choices=[('mejora', 'Mejora'), ('baja', 'Baja'), ('mantiene', 'Se Mantiene')], help_text='Comparación con el promedio del mes anterior.', max_length=10, null=True, verbose_name='Tendencia de Valoración'),
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='valoracion_promedio_mes',
            field=models.FloatField(blank=True, help_text='Promedio de las valoraciones diarias (1-5 estrellas) de los seguimientos.', null=True, verbose_name='Valoración Promedio del Mes'),
        ),
        migrations.RemoveField(
            model_name='desarrollonino',
            name='dimension_cognitiva',
        ),
        migrations.RemoveField(
            model_name='desarrollonino',
            name='dimension_comunicativa',
        ),
        migrations.RemoveField(
            model_name='desarrollonino',
            name='dimension_corporal',
        ),
        migrations.RemoveField(
            model_name='desarrollonino',
            name='dimension_socio_afectiva',
        ),
        migrations.RemoveField(
            model_name='desarrollonino',
            name='rating_cognitiva',
        ),
        migrations.RemoveField(
            model_name='desarrollonino',
            name='rating_comunicativa',
        ),
        migrations.RemoveField(
            model_name='desarrollonino',
            name='rating_corporal',
        ),
        migrations.RemoveField(
            model_name='desarrollonino',
            name='rating_socio_afectiva',
        ),
        migrations.CreateModel(
            name='SeguimientoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('participacion', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('no_aplica', 'No Aplica')], max_length=10, verbose_name='¿Cómo participó el niño/a en la actividad?')),
                ('comportamiento_logro', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('bajo', 'Bajo'), ('dificultad', 'Presentó Dificultad')], max_length=10, verbose_name='Comportamiento, interés y nivel de logro')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del educador')),
                ('valoracion', models.PositiveSmallIntegerField(blank=True, help_text='Calificación de 1 a 5 estrellas.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Valoración del día')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_diarios', to='core.nino')),
                ('planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_diarios', to='planeaciones.planeacion')),
            ],
            options={
                'verbose_name': 'Seguimiento Diario',
                'verbose_name_plural': 'Seguimientos Diarios',
                'ordering': ['-fecha', 'nino'],
                'unique_together': {('nino', 'fecha')},
            },
        ),
    ]
