# Generated by Django 5.2.8 on 2025-11-20 04:20

from django.db import migrations


def fix_database_schema(apps, schema_editor):
    """
    Corrige el esquema de la base de datos para que coincida con el modelo actual.
    Elimina columnas viejas y agrega las nuevas si es necesario, usando SQL directo.
    """
    DesarrolloNino = apps.get_model('desarrollo', 'DesarrolloNino')
    table = DesarrolloNino._meta.db_table

    fields_to_remove = [
        'dimension_cognitiva', 'dimension_comunicativa', 'dimension_socio_afectiva',
        'dimension_corporal', 'rating_cognitiva', 'rating_comunicativa',
        'rating_corporal', 'rating_socio_afectiva',
    ]
    fields_to_add = [
        ('evaluacion_cognitiva', 'TEXT'),
        ('evaluacion_comunicativa', 'TEXT'),
        ('evaluacion_socio_afectiva', 'TEXT'),
        ('evaluacion_corporal', 'TEXT'),
        ('evaluacion_autonomia', 'TEXT'),
        ('valoracion_promedio_mes', 'REAL'),
        ('tendencia_valoracion', 'VARCHAR(10)'),
        ('comportamiento_frecuente', 'VARCHAR(50)'),
        ('participacion_frecuente', 'VARCHAR(50)'),
        ('fortalezas_mes', 'TEXT'),
        ('aspectos_a_mejorar', 'TEXT'),
        ('conclusion_general', 'TEXT'),
        ('alertas_mes', 'TEXT'),
        ('recomendaciones_personales', 'TEXT'),
        ('observaciones_adicionales', 'TEXT'),
    ]

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"PRAGMA table_info({table})")
        existing_columns = {row[1] for row in cursor.fetchall()}

        # Eliminar columnas viejas si existen (solo SQLite >= 3.35.0 soporta DROP COLUMN)
        for field in fields_to_remove:
            if field in existing_columns:
                try:
                    cursor.execute(f'ALTER TABLE {table} DROP COLUMN {field}')
                except Exception:
                    pass  # Si no soporta DROP COLUMN, ignorar

        # Agregar columnas nuevas si no existen
        for field, sqltype in fields_to_add:
            if field not in existing_columns:
                cursor.execute(f'ALTER TABLE {table} ADD COLUMN {field} {sqltype}')


def no_op_reverse(apps, schema_editor):
    """
    Esta migración es una corrección unidireccional. No hacemos nada si se revierte.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0004_alter_desarrollonino_options_and_more'),
    ]

    # IMPORTANTE: Esta migración no debe afectar el estado del proyecto de Django,
    # solo debe afectar la base de datos. Por eso usamos RunPython y no AddField/RemoveField.
    # El estado del proyecto ya es correcto gracias a la migración 0004.
    # Esta migración es "elidable", lo que significa que no se ejecutará en una base de datos nueva.
    elidable = True

    operations = [
        migrations.RunPython(fix_database_schema, reverse_code=no_op_reverse),
    ]
