# Generated by Django 5.2.8 on 2025-11-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0005_auto_20251119_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desarrollonino',
            name='valoracion_promedio_mes',
        ),
        migrations.AddField(
            model_name='desarrollonino',
            name='logro_mes',
            field=models.CharField(blank=True, choices=[('Alto', 'Alto'), ('Adecuado', 'Adecuado'), ('En Proceso', 'En Proceso')], help_text='Categoría cualitativa basada en la frecuencia de valoraciones diarias.', max_length=20, null=True, verbose_name='Logro General del Mes'),
        ),
        migrations.AlterField(
            model_name='desarrollonino',
            name='tendencia_valoracion',
            field=models.CharField(blank=True, choices=[('Avanza', 'Avanza'), ('Retrocede', 'Retrocede'), ('Se Mantiene', 'Se Mantiene'), ('Sin datos previos', 'Sin datos previos')], help_text='Comparación con el promedio del mes anterior.', max_length=20, null=True, verbose_name='Tendencia de Valoración'),
        ),
    ]
