# Generated by Django 5.2.8 on 2025-11-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0006_remove_desarrollonino_valoracion_promedio_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollonino',
            name='porcentaje_asistencia',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje de días presentes sobre los días hábiles del mes.', null=True, verbose_name='Porcentaje de Asistencia Mensual'),
        ),
    ]
