# Generated by Django 5.2.8 on 2025-11-26 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0007_desarrollonino_porcentaje_asistencia'),
        ('planeaciones', '0005_dimension_planeacion_dimensiones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientodiario',
            name='comportamiento_logro',
        ),
        migrations.RemoveField(
            model_name='seguimientodiario',
            name='participacion',
        ),
        migrations.AddField(
            model_name='seguimientodiario',
            name='comportamiento_general',
            field=models.CharField(blank=True, choices=[('participativo', 'Participativo'), ('aislado', 'Aislado'), ('impulsivo', 'Impulsivo'), ('inquieto', 'Inquieto'), ('tranquilo', 'Tranquilo'), ('colaborativo', 'Colaborativo')], max_length=20, null=True, verbose_name='Comportamiento general del niño'),
        ),
        migrations.AddField(
            model_name='seguimientodiario',
            name='estado_emocional',
            field=models.CharField(blank=True, choices=[('alegre', 'Alegre'), ('tranquilo', 'Tranquilo'), ('curioso', 'Curioso'), ('motivado', 'Motivado'), ('carinoso', 'Cariñoso'), ('cansado', 'Cansado'), ('triste', 'Triste'), ('ansioso', 'Ansioso'), ('frustrado', 'Frustrado'), ('enojado', 'Enojado / Irritado'), ('timido', 'Tímido / Inseguro'), ('aislado_emocional', 'Aislado (poco participativo)')], max_length=20, null=True, verbose_name='Estado emocional del niño'),
        ),
        migrations.AddField(
            model_name='seguimientodiario',
            name='observacion_relevante',
            field=models.BooleanField(default=False, help_text='Marcar si la observación debe ser considerada en los informes de desarrollo.', verbose_name='¿Esta observación es relevante para el desarrollo del niño?'),
        ),
        migrations.CreateModel(
            name='EvaluacionDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desempeno', models.CharField(choices=[('alto', 'Alto'), ('adecuado', 'Adecuado'), ('proceso', 'En Proceso'), ('bajo', 'Bajo')], max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeaciones.dimension')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_dimension', to='desarrollo.seguimientodiario')),
            ],
            options={
                'unique_together': {('seguimiento', 'dimension')},
            },
        ),
    ]
