# Generated by Django 5.2.8 on 2025-11-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0008_remove_seguimientodiario_comportamiento_logro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientodiario',
            name='observacion_relevante',
            field=models.BooleanField(blank=True, default=False, help_text='Marcar si la observación debe ser considerada en los informes de desarrollo.', verbose_name='¿Esta observación es relevante para el desarrollo del niño?'),
        ),
    ]
